'use client';

import React, { useState } from 'react';
import { Patient } from '@/data/mockPatients';
import { RiskBadge } from '@/components/RiskBadge';
import {
  FileText,
  Printer,
  Copy,
  Check,
  X,
  ShieldAlert,
  Stethoscope,
  Download,
} from 'lucide-react';

interface ClinicalReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  patient: Patient;
}

export function ClinicalReportModal({
  isOpen,
  onClose,
  patient,
}: ClinicalReportModalProps) {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleCopy = () => {
    const reportText = `
MEDGUARD AI CLINICAL CONSULTATION NOTE
PATIENT: ${patient.name} | MRN: ${patient.mrn} | DOB: ${patient.dob} (${patient.age}y ${patient.gender})
CONSULT DATE: ${new Date().toLocaleDateString()} | PHYSICIAN: ${patient.primaryDoctor}

CLINICAL VITALS & BIOMARKERS:
- BP: ${patient.bloodPressure} | HR: ${patient.heartRate} bpm
- eGFR: ${patient.eGFR} mL/min (CKD Stage 3b) | Creatinine: ${patient.creatinine} mg/dL
- Potassium: ${patient.potassium} mEq/L ${patient.potassium > 5 ? '(HYPERKALEMIA ALERT)' : ''}
${patient.inr ? `- INR: ${patient.inr} (SUPRATHERAPEUTIC BLEED HAZARD)` : ''}

ASSESSMENT & POLYPHARMACY AUDIT:
- Composite Polypharmacy Risk Score: ${patient.polypharmacyScore} / 100 [${patient.riskLevel} RISK]
- Anticholinergic Cognitive Burden (ACB): ${patient.totalAcbScore} (Delirium/Dementia Hazard)
- Fall & Sedation Index: ${patient.fallRiskScore}/10
- Critical Drug Interactions Detected: ${patient.interactions.length}
- Prescribing Cascades: ${patient.cascades.length > 0 ? patient.cascades.map(c => `${c.primaryDrug} -> ${c.secondaryDrug}`).join(', ') : 'None'}

ACTIVE MEDICATIONS (${patient.medications.length}):
${patient.medications.map(m => `- ${m.name} ${m.dosage} (${m.frequency}) [Indication: ${m.indication}]`).join('\n')}

AI DEPRESCRIBING RECOMMENDATIONS & PLAN:
${patient.recommendations.map((r, i) => `${i + 1}. [${r.priority}] ${r.action}: ${r.drugName} - Rationale: ${r.clinicalRationale} (Alternative: ${r.suggestedAlternative || 'None'})`).join('\n')}

MONITORING TIMELINE:
- Repeat basic metabolic panel & electrolytes in 48-72 hours.
- Evaluate clinical resolution of fall hazard and sedative burden at 2-week clinical follow-up.
    `.trim();

    navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 3000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs animate-in fade-in duration-200">
      <div className="bg-white rounded-3xl border border-slate-200 shadow-2xl max-w-3xl w-full max-h-[92vh] flex flex-col overflow-hidden animate-in zoom-in-95 duration-200">
        
        {/* Header Actions */}
        <div className="p-4 border-b border-slate-100 flex items-center justify-between bg-slate-50/80 no-print">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-xl bg-slate-900 text-white flex items-center justify-center">
              <FileText className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-slate-900">
                Clinical Polypharmacy Consultation Report
              </h3>
              <p className="text-[11px] text-slate-500 font-mono">
                EHR-Exportable SOAP Format • Generated by MedGuard AI
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl border border-slate-200 bg-white hover:bg-slate-50 text-slate-700 text-xs font-semibold transition-colors cursor-pointer"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied to Clipboard' : 'Copy Text'}</span>
            </button>

            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-slate-900 hover:bg-slate-800 text-white text-xs font-semibold transition-colors shadow-2xs cursor-pointer"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / Save PDF</span>
            </button>

            <button
              onClick={onClose}
              className="p-1.5 rounded-xl text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition-colors ml-1 cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Printable Medical Document Body */}
        <div className="p-8 overflow-y-auto space-y-6 text-xs text-slate-800 leading-relaxed font-sans bg-white print:p-0">
          
          {/* Institutional Header */}
          <div className="border-b-2 border-slate-900 pb-4 flex items-start justify-between">
            <div>
              <div className="flex items-center gap-2 text-slate-900 font-extrabold text-base tracking-tight">
                <ShieldAlert className="w-5 h-5 text-teal-600" />
                MEDGUARD CLINICAL HEALTH SYSTEM
              </div>
              <div className="text-[11px] text-slate-500 font-medium">
                Comprehensive Geriatric Polypharmacy & Medication Therapy Management (MTM)
              </div>
            </div>
            <div className="text-right text-[11px] text-slate-500 font-mono">
              <div>Date: {new Date().toLocaleDateString()}</div>
              <div>Report ID: MG-AUDIT-{patient.mrn}</div>
            </div>
          </div>

          {/* Patient Demographics Table */}
          <div className="bg-slate-50 p-3.5 rounded-xl border border-slate-200 grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
            <div>
              <span className="text-slate-400 text-[10px] uppercase font-bold block">Patient Name</span>
              <span className="font-bold text-slate-900">{patient.name}</span>
            </div>
            <div>
              <span className="text-slate-400 text-[10px] uppercase font-bold block">MRN</span>
              <span className="font-mono font-bold text-slate-800">{patient.mrn}</span>
            </div>
            <div>
              <span className="text-slate-400 text-[10px] uppercase font-bold block">Age / Gender</span>
              <span className="font-bold text-slate-800">{patient.age} yrs • {patient.gender}</span>
            </div>
            <div>
              <span className="text-slate-400 text-[10px] uppercase font-bold block">Attending Physician</span>
              <span className="font-bold text-slate-800">{patient.primaryDoctor}</span>
            </div>
          </div>

          {/* Clinical Assessment Summary */}
          <div>
            <h4 className="font-bold uppercase tracking-wider text-slate-900 text-xs border-b border-slate-200 pb-1 mb-2.5 flex items-center justify-between">
              <span>1. Polypharmacy Safety Audit & Risk Stratification</span>
              <RiskBadge level={patient.riskLevel} size="sm" score={patient.polypharmacyScore} />
            </h4>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 p-3 rounded-xl bg-slate-50/60 border border-slate-200 mb-2">
              <div>
                <span className="text-[10px] text-slate-500 font-bold uppercase block">Polypharmacy Score:</span>
                <span className="text-base font-extrabold font-mono text-slate-900">{patient.polypharmacyScore}/100</span>
              </div>
              <div>
                <span className="text-[10px] text-slate-500 font-bold uppercase block">Anticholinergic Burden:</span>
                <span className="text-base font-extrabold font-mono text-slate-900">{patient.totalAcbScore} (High ACB)</span>
              </div>
              <div>
                <span className="text-[10px] text-slate-500 font-bold uppercase block">Fall / Sedation Index:</span>
                <span className="text-base font-extrabold font-mono text-slate-900">{patient.fallRiskScore} / 10</span>
              </div>
            </div>
            <p className="text-slate-700">
              Patient exhibits multi-target polypharmacy risk with {patient.medications.length} concurrent oral prescriptions. Significant collision between pharmacokinetic clearing capacity (eGFR {patient.eGFR} mL/min) and concurrent interacting therapies.
            </p>
          </div>

          {/* Critical Interactions Table */}
          <div>
            <h4 className="font-bold uppercase tracking-wider text-slate-900 text-xs border-b border-slate-200 pb-1 mb-2">
              2. Significant Drug-Drug Interactions ({patient.interactions.length})
            </h4>
            <div className="space-y-2">
              {patient.interactions.map((ddi) => (
                <div key={ddi.id} className="p-2.5 rounded-lg border border-slate-200 bg-slate-50/40">
                  <div className="flex items-center justify-between font-bold text-slate-900 mb-0.5">
                    <span>{ddi.drug1} + {ddi.drug2}</span>
                    <span className="text-[10px] uppercase font-bold text-rose-700">{ddi.severity} Severity</span>
                  </div>
                  <div className="text-slate-600 text-[11px] mb-1">{ddi.mechanism}</div>
                  <div className="text-rose-800 font-medium text-[11px]">Recommendation: {ddi.recommendation}</div>
                </div>
              ))}
            </div>
          </div>

          {/* Deprescribing Plan */}
          <div>
            <h4 className="font-bold uppercase tracking-wider text-slate-900 text-xs border-b border-slate-200 pb-1 mb-2">
              3. Deprescribing Roadmap & Taper Schedule
            </h4>
            <div className="space-y-2">
              {patient.recommendations.map((rec, i) => (
                <div key={rec.id} className="p-2.5 rounded-lg bg-slate-50 border border-slate-200">
                  <div className="font-bold text-slate-900 flex items-center justify-between">
                    <span>Phase {i + 1} ({rec.priority}): {rec.action} {rec.drugName}</span>
                    <span className="text-emerald-700 font-bold text-[10px] font-mono">+{rec.expectedScoreImprovement} Pts Safety</span>
                  </div>
                  <div className="text-slate-600 text-[11px] mt-0.5">{rec.clinicalRationale}</div>
                  {rec.suggestedAlternative && (
                    <div className="text-teal-800 font-semibold text-[11px] mt-0.5">
                      Alternative: {rec.suggestedAlternative}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Physician Sign-Off */}
          <div className="pt-6 border-t border-slate-200 grid grid-cols-2 gap-8 text-[11px] text-slate-500">
            <div>
              <div className="h-8 border-b border-slate-300 mb-1" />
              <div>Reviewing Clinician Signature / Credentials</div>
            </div>
            <div>
              <div className="h-8 border-b border-slate-300 mb-1" />
              <div>Clinical Pharmacist / Geriatric Fellow Signature</div>
            </div>
          </div>

        </div>

      </div>
    </div>
  );
}
