"""phase2_consultation_expansion

Revision ID: f6a1e71c9061
Revises: 6e74acb7398a
Create Date: 2026-09-27 04:52:18.378294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a1e71c9061'
down_revision: Union[str, Sequence[str], None] = '6e74acb7398a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('consultation_id', sa.String(length=36), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('attachment_type', sa.String(length=50), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_attachments_consultation_id'), 'consultation_attachments', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_consultation_attachments_id'), 'consultation_attachments', ['id'], unique=False)
    op.create_table('consultation_medications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('consultation_id', sa.String(length=36), nullable=False),
    sa.Column('medicine_name', sa.String(length=200), nullable=False),
    sa.Column('dose', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('scheduled_times', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.String(length=50), nullable=True),
    sa.Column('end_date', sa.String(length=50), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_medications_consultation_id'), 'consultation_medications', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_consultation_medications_id'), 'consultation_medications', ['id'], unique=False)
    op.add_column('consultation_messages', sa.Column('attachment_id', sa.String(length=36), nullable=True))
    op.add_column('consultation_messages', sa.Column('read_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'consultation_messages', 'consultation_attachments', ['attachment_id'], ['id'], ondelete='SET NULL')
    op.add_column('consultations', sa.Column('appointment_id', sa.String(length=36), nullable=True))
    op.add_column('consultations', sa.Column('started_at', sa.DateTime(), nullable=False))
    op.add_column('consultations', sa.Column('last_activity_at', sa.DateTime(), nullable=False))
    op.alter_column('consultations', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.create_index(op.f('ix_consultations_appointment_id'), 'consultations', ['appointment_id'], unique=False)
    op.create_foreign_key(None, 'consultations', 'appointments', ['appointment_id'], ['id'], ondelete='SET NULL')
    op.add_column('medication_logs', sa.Column('scheduled_date', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_medication_logs_scheduled_date'), 'medication_logs', ['scheduled_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medication_logs_scheduled_date'), table_name='medication_logs')
    op.drop_column('medication_logs', 'scheduled_date')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'consultations', type_='foreignkey')
    op.drop_index(op.f('ix_consultations_appointment_id'), table_name='consultations')
    op.alter_column('consultations', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('consultations', 'last_activity_at')
    op.drop_column('consultations', 'started_at')
    op.drop_column('consultations', 'appointment_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'consultation_messages', type_='foreignkey')
    op.drop_column('consultation_messages', 'read_at')
    op.drop_column('consultation_messages', 'attachment_id')
    op.drop_index(op.f('ix_consultation_medications_id'), table_name='consultation_medications')
    op.drop_index(op.f('ix_consultation_medications_consultation_id'), table_name='consultation_medications')
    op.drop_table('consultation_medications')
    op.drop_index(op.f('ix_consultation_attachments_id'), table_name='consultation_attachments')
    op.drop_index(op.f('ix_consultation_attachments_consultation_id'), table_name='consultation_attachments')
    op.drop_table('consultation_attachments')
    # ### end Alembic commands ###
